[project]
name = "photo-downloader"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "dropbox>=12.0.2",
    "fastapi>=0.111.0",
    "playwright>=1.55.0",
    "requests>=2.32.5",
    "uvicorn[standard]>=0.30.0",
]
